### ISSUE TITLE
Event generation using lcf_reader mrbgem.

### ISSUE THREAD

**Issue by take-cheeze** [EasyRPG/TestGame#23]
Since binary data isn't diffable with git we need a better way to review TestGame review.
What I'm thinking is that to generate TestGame event with mruby script using DSL.
Additionally it can have test that will be runned in mruby player using comment event command.

**Comment by fdelapena** [comment]
This has been superseded with the event tracer, which generates logs from both interpreters.
There are two parts: A DynRPG Plug-in in RPG_RT and an equivalent code in Player.
Then it only needs a log comparison. If equals, test is passed.

DynRPG Plugin: [Ghabry/dynrpg-eventtracer](https://github.com/Ghabry/dynrpg-eventtracer).
Player code: [Ghabry/Player event_unittest branch](https://github.com/Ghabry/easyrpg-player/tree/event_unittest) ([git compare](https://github.com/EasyRPG/Player/compare/master...Ghabry:event_unittest)).
