### ISSUE TITLE
Proposal: Separate test game rooms into smaller projects

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/TestGame#29]
The purpose of this is to play them from the new game browser since Player 0.4, making tests navigation faster and easier to maintain (adding new cases without modifying existing data of a single file.

It would allow also to classify here specific issues related to player or liblcf bugs and easier management even upload automation to play them from Emscripten.

**Comment by Ghabry** [comment]
What are the advantages of this? I mean you still require to edit single maps to add new test cases. Just in different projects.

**Comment by fdelapena** [comment]
Emscripten already supports start map ID and position, so this issue is nonsense today. Closing.
