### ISSUE TITLE
FaceSets missing

### ISSUE THREAD

**Issue by Rinnegatamante** [EasyRPG/TestGame#32]
Looks like facesets are missing.

**Comment by Ghabry** [comment]
Yepp because we don't have replacement graphics for this yet and the original Runtime Package does not allow distribution. :(

You can get the assets from here: http://crankeye.com/?page=downloads (RPG Maker 2000 RTP)

**Comment by Ghabry** [comment]
You can also use our ugly replacement graphics from the web version:
To get an asset just use the URL ```https://easy-rpg.org/play/games/default``` and append what is missing: ```/FaceSet/Chara1.png```

https://easy-rpg.org/play/games/default/FaceSet/Chara1.png
